-- =============================================================================
-- 0002 — Correlacion con banco
--
-- Registro manual del saldo que el banco reporta cada dia, en Bs y en USD, para
-- contrastarlo con lo que el sistema dice que debio entrar (cobros por metodos
-- que NO son efectivo ni credito: pago movil, transferencia, punto de venta,
-- Zelle, Binance).
--
-- Es una tabla AISLADA: nada del POS, la caja, los reportes ni el dashboard la
-- lee ni la escribe. Solo la pantalla "Correlacion con banco". Borrarla no
-- afecta ninguna otra cifra del sistema.
--
-- Idempotente: correrla de nuevo no duplica nada.
-- =============================================================================

CREATE TABLE IF NOT EXISTS banco_saldos (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sucursal_id    BIGINT NOT NULL,
  fecha          DATE NOT NULL,
  -- Saldos declarados. Se permiten negativos: una cuenta puede quedar en rojo.
  saldo_bs       DECIMAL(18,2) NOT NULL DEFAULT 0,
  saldo_usd      DECIMAL(14,2) NOT NULL DEFAULT 0,
  observaciones  VARCHAR(255),
  usuario_id     BIGINT,
  creado_en      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMPTZ(3),
  PRIMARY KEY (id)
);

-- Un solo saldo por sucursal y dia: registrar dos veces el mismo dia lo actualiza.
CREATE UNIQUE INDEX IF NOT EXISTS uq_banco_saldos_dia ON banco_saldos (sucursal_id, fecha);
CREATE INDEX IF NOT EXISTS ix_banco_saldos_fecha ON banco_saldos (fecha);

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_banco_saldos_sucursal') THEN
    ALTER TABLE banco_saldos ADD CONSTRAINT fk_banco_saldos_sucursal
      FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_banco_saldos_usuario') THEN
    ALTER TABLE banco_saldos ADD CONSTRAINT fk_banco_saldos_usuario
      FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL;
  END IF;
END $$;

DROP TRIGGER IF EXISTS trg_banco_saldos_actualizado ON banco_saldos;
CREATE TRIGGER trg_banco_saldos_actualizado BEFORE UPDATE ON banco_saldos
  FOR EACH ROW EXECUTE FUNCTION actualizar_actualizado_en();

COMMENT ON TABLE banco_saldos IS 'Saldo bancario declarado por dia (Bs y USD). Aislado del resto del sistema';

-- -----------------------------------------------------------------------------
-- Permisos del modulo
-- -----------------------------------------------------------------------------
INSERT INTO permisos (codigo, modulo, accion, descripcion) VALUES
  ('banco.ver', 'banco', 'ver', 'Ver la correlacion con banco'),
  ('banco.registrar', 'banco', 'registrar', 'Registrar el saldo bancario del dia')
ON CONFLICT (codigo) DO NOTHING;

-- Se otorgan a Administrador (1) y Supervisor (2), que son los que cuadran plata.
INSERT INTO rol_permisos (rol_id, permiso_id)
SELECT r.rol_id, p.id
  FROM (VALUES (1), (2)) AS r(rol_id)
  CROSS JOIN permisos p
 WHERE p.codigo IN ('banco.ver', 'banco.registrar')
ON CONFLICT DO NOTHING;
