-- =============================================================================
-- 0006 — Vuelto en la moneda que se entrega + pago de las entradas a credito
--
-- Dos cosas que el mostrador hace todos los dias y la base no sabia registrar.
--
-- 1) EL VUELTO NO SIEMPRE SALE EN LA MONEDA DEL COBRO
--    El cliente debe $ 9,50, paga con 4.000 Bs y el cajero le devuelve el vuelto
--    en dolares porque no tiene billetes chicos de Bs (o al reves). Hasta ahora
--    `abonos.cambio_moneda` se leia SIEMPRE en la moneda del abono, asi que ese
--    gesto real no se podia guardar: la gaveta quedaba con menos dolares de los
--    que decia el arqueo. `pagos` ya tiene la columna para esto
--    (`cambio_moneda_codigo`); aca se le copia a `abonos`.
--
--    Eso obliga a aflojar ck_abonos_recibido: recibido = abonado + vuelto solo
--    cuadra cuando ambos estan en la MISMA moneda. Si el vuelto se dio en la otra,
--    la igualdad se hace contra la tasa del dia y la valida el servicio, no el CHECK
--    (que no puede convertir monedas sin arrastrar el redondeo del piso).
--
-- 2) LAS ENTRADAS A CREDITO NO SE PODIAN PAGAR
--    Una entrada de mercancia a credito abre `compras.saldo_pendiente` y le suma
--    al proveedor... y ahi se quedaba para siempre: no habia ninguna forma de
--    registrar que se le pago. La entrada aparecia "Debes $ X" incluso despues de
--    haberle pagado al proveedor en la cara.
--
--    `compra_pagos` es a la compra lo que `abonos` es al credito del cliente: una
--    fila por cada plata que sale, con su moneda, su tasa congelada y su
--    equivalente en USD. El saldo vive en `compras.saldo_pendiente`; esta tabla es
--    el detalle de como se fue bajando.
--
-- Idempotente: correrla dos veces no hace nada la segunda vez.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Moneda del vuelto en los abonos
-- -----------------------------------------------------------------------------
ALTER TABLE abonos ADD COLUMN IF NOT EXISTS cambio_moneda_codigo tipo_metodo_pago_moneda;

-- Los abonos historicos solo podian devolver en la moneda del abono.
UPDATE abonos
   SET cambio_moneda_codigo = moneda
 WHERE cambio_moneda_codigo IS NULL AND COALESCE(cambio_moneda, 0) > 0;

ALTER TABLE abonos DROP CONSTRAINT IF EXISTS ck_abonos_recibido;
ALTER TABLE abonos ADD CONSTRAINT ck_abonos_recibido CHECK (
  monto_recibido_moneda IS NULL
  OR COALESCE(cambio_moneda, 0) = 0
  -- Vuelto en la otra moneda: la igualdad se verifica contra la tasa, no aca.
  OR cambio_moneda_codigo IS DISTINCT FROM moneda
  OR monto_recibido_moneda = monto_moneda + cambio_moneda
);

COMMENT ON COLUMN abonos.cambio_moneda_codigo IS 'Moneda en la que se entrego el vuelto; puede no ser la del abono';

-- -----------------------------------------------------------------------------
-- 2. Pagos de una entrada de mercancia (cuenta por pagar al proveedor)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS compra_pagos (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  compra_id          BIGINT NOT NULL,
  sucursal_id        BIGINT NOT NULL,
  -- Nulo cuando se paga por transferencia sin caja abierta: la plata no salio de la gaveta.
  turno_caja_id      BIGINT,
  metodo_pago_id     BIGINT NOT NULL,
  usuario_id         BIGINT NOT NULL,
  fecha              TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  moneda             tipo_metodo_pago_moneda NOT NULL,
  monto_moneda       DECIMAL(18,4) NOT NULL CHECK (monto_moneda > 0),
  tasa_aplicada      DECIMAL(18,6) NOT NULL CHECK (tasa_aplicada > 0),
  monto_usd          DECIMAL(14,2) NOT NULL CHECK (monto_usd > 0),
  referencia         VARCHAR(60),
  observaciones      VARCHAR(255),
  estado             VARCHAR(10) NOT NULL DEFAULT 'APLICADO',
  clave_idempotencia UUID,
  creado_en          TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_cp_compra   ON compra_pagos (compra_id, fecha);
CREATE INDEX IF NOT EXISTS ix_cp_sucursal ON compra_pagos (sucursal_id, fecha);
CREATE INDEX IF NOT EXISTS ix_cp_turno    ON compra_pagos (turno_caja_id);
CREATE INDEX IF NOT EXISTS ix_cp_metodo   ON compra_pagos (metodo_pago_id);
CREATE INDEX IF NOT EXISTS ix_cp_usuario  ON compra_pagos (usuario_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cp_idem ON compra_pagos (clave_idempotencia)
  WHERE clave_idempotencia IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cp_compra') THEN
    ALTER TABLE compra_pagos ADD CONSTRAINT fk_cp_compra   FOREIGN KEY (compra_id)      REFERENCES compras(id)      ON DELETE RESTRICT;
    ALTER TABLE compra_pagos ADD CONSTRAINT fk_cp_sucursal FOREIGN KEY (sucursal_id)    REFERENCES sucursales(id)   ON DELETE RESTRICT;
    ALTER TABLE compra_pagos ADD CONSTRAINT fk_cp_turno    FOREIGN KEY (turno_caja_id)  REFERENCES turnos_caja(id)  ON DELETE RESTRICT;
    ALTER TABLE compra_pagos ADD CONSTRAINT fk_cp_metodo   FOREIGN KEY (metodo_pago_id) REFERENCES metodos_pago(id) ON DELETE RESTRICT;
    ALTER TABLE compra_pagos ADD CONSTRAINT fk_cp_usuario  FOREIGN KEY (usuario_id)     REFERENCES usuarios(id)     ON DELETE RESTRICT;
    ALTER TABLE compra_pagos ADD CONSTRAINT ck_cp_estado   CHECK (estado IN ('APLICADO', 'ANULADO'));
  END IF;
END $$;

COMMENT ON TABLE compra_pagos IS 'Plata que sale para pagarle al proveedor una entrada a credito';

-- Las entradas de CONTADO nacieron pagadas; las viejas a credito conservan su saldo.
UPDATE compras SET saldo_pendiente = 0
 WHERE condicion_pago = 'CONTADO' AND saldo_pendiente <> 0;
