-- =============================================================================
-- 0008 — Ventas en espera (carritos guardados en el POS)
--
-- EL PROBLEMA
-- El cliente arma su compra, se queda pensando y detras hay cola. Hoy el cajero
-- solo puede cobrar o cancelar: el carrito vive en el navegador (`gochito.carrito`)
-- y es UNO solo, asi que atender al siguiente borra lo que el primero llevaba.
--
-- LA SOLUCION
-- Una gaveta de carritos aparcados, con el nombre con el que el cajero reconoce a
-- la persona. Se guarda en la base y no en el navegador para que sobreviva a un
-- refresco, a que se cierre sesion y para que se pueda retomar desde otra caja de
-- la misma sucursal: el cliente que dejo la compra en la caja 1 puede terminarla
-- en la caja 2.
--
-- ESTO NO ES UNA VENTA
-- No consume consecutivo, no toca inventario, no reserva stock y no entra en
-- ningun reporte. Es un borrador. De ahi que viva en su propia tabla y no como un
-- estado mas de `ventas`: una fila en `ventas` implica numero de documento y
-- aparece en el historial, y un carrito que quiza nunca se cobre no es un
-- documento.
--
-- EL CARRITO VA EN JSONB
-- Es el estado del POS tal cual (renglon, precio elegido, si va al mayor, el
-- descuento que el cajero dio a mano). Es un borrador de pantalla, no un asiento:
-- normalizarlo en una tabla de detalle obligaria a migrar el esquema cada vez que
-- el carrito gane un campo, y no hay nada que consultar por dentro.
--
-- Los precios guardados son una FOTO del momento. Al retomar la venta el backend
-- devuelve tambien el producto vigente para refrescar existencia y precio de lista;
-- lo que el cajero cambio a mano se respeta (ver pos/espera.service.ts).
--
-- Idempotente: se puede reintentar sin efecto.
-- =============================================================================

CREATE TABLE IF NOT EXISTS ventas_en_espera (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sucursal_id    BIGINT NOT NULL,
  usuario_id     BIGINT NOT NULL,
  cliente_id     BIGINT,
  -- Con que la llama el cajero: el nombre del cliente, o "el señor de la moto".
  nombre         VARCHAR(80) NOT NULL,
  nota           VARCHAR(200),
  -- Total y numero de renglones al guardar: son para pintar la lista sin abrir
  -- el JSON. La cuenta de verdad se recalcula al retomar.
  total_usd      DECIMAL(14,2) NOT NULL DEFAULT 0 CHECK (total_usd >= 0),
  renglones      INTEGER NOT NULL DEFAULT 0 CHECK (renglones >= 0),
  carrito        JSONB NOT NULL,
  creado_en      TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en TIMESTAMPTZ(3),
  PRIMARY KEY (id)
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_espera_sucursal') THEN
    ALTER TABLE ventas_en_espera ADD CONSTRAINT fk_espera_sucursal
      FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE RESTRICT;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_espera_usuario') THEN
    ALTER TABLE ventas_en_espera ADD CONSTRAINT fk_espera_usuario
      FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT;
  END IF;
  -- SET NULL y no RESTRICT: borrar un cliente no puede quedar bloqueado por un
  -- borrador de carrito. El nombre queda igual en `nombre`.
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_espera_cliente') THEN
    ALTER TABLE ventas_en_espera ADD CONSTRAINT fk_espera_cliente
      FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL;
  END IF;
END $$;

-- La lista del POS siempre es "las de esta sucursal, la mas reciente arriba".
CREATE INDEX IF NOT EXISTS ix_espera_sucursal ON ventas_en_espera (sucursal_id, creado_en DESC);

COMMENT ON TABLE ventas_en_espera IS
  'Carritos aparcados en el POS. Borradores: no consumen consecutivo ni tocan inventario';
COMMENT ON COLUMN ventas_en_espera.carrito IS
  'Estado del carrito del POS tal cual. Los precios son una foto; al retomar se refrescan';
