-- =============================================================================
-- 0009 — El costo del producto: semilla contra costo real
--
-- EL PROBLEMA
-- Al crear un producto se escribe un "costo inicial" que se guarda en
-- producto_stock.costo_promedio con cantidad 0. Ese numero es un estimado que
-- teclea quien da de alta el producto, no una compra: nadie pago eso.
--
-- Mientras la existencia sea 0 no molesta, porque la primera entrada de mercancia
-- lo reemplaza sola (el promedio ponderado divide por un stock anterior de cero).
-- Pero si la existencia se carga por AJUSTE de inventario —que mueve cantidades y
-- nunca costos— el producto queda con unidades valorizadas al estimado, y la
-- primera compra de verdad lo promedia con el:
--
--   costo inicial $ 1,00 (inventado) + 10 u cargadas por ajuste
--   entrada real  10 u a $ 1,20
--   CPP = (10 x 1,00 + 10 x 1,20) / 20 = $ 1,10   <- el $ 1,00 inventado pesa igual
--                                                    que el costo que si se pago
--
-- Ese CPP contaminado es el que se congela como snapshot de costo en cada venta
-- (ADR-001), asi que el error se propaga a la utilidad de todos los reportes.
-- Y el caso peor es el mas comun: costo inicial en 0, existencia cargada por
-- ajuste, ventas con utilidad del 100% que no existe.
--
-- LA SOLUCION
-- Distinguir un costo SEMILLA (lo que alguien estimo al crear el producto) de un
-- costo REAL (el que salio de una entrada de mercancia, de un ajuste con costo o
-- de una correccion explicita). Mientras el costo sea semilla, la siguiente
-- entrada lo PISA en vez de promediarlo. Ya confirmado, vuelve el promedio
-- ponderado movil de siempre.
--
--   costo_confirmado = FALSE -> lo que hay es un estimado, no pesa en el promedio
--   costo_confirmado = TRUE  -> hay plata real detras, se promedia
--
-- La bandera vive en producto_stock y no en productos porque el costo se valoriza
-- por sucursal: la misma referencia puede tener costo real en una tienda y solo el
-- estimado en otra que todavia no ha recibido mercancia.
--
-- BACKFILL
-- Se marca como confirmado todo producto que ya tenga al menos una ENTRADA_COMPRA
-- en el ledger: ese costo ya salio de una compra, no hay nada que pisar.
-- =============================================================================

ALTER TABLE producto_stock
  ADD COLUMN IF NOT EXISTS costo_confirmado BOOLEAN NOT NULL DEFAULT FALSE;

COMMENT ON COLUMN producto_stock.costo_confirmado IS
  'FALSE = costo_promedio es la semilla tecleada al crear el producto; la proxima entrada lo pisa. TRUE = salio de una entrada, ajuste con costo o correccion.';

UPDATE producto_stock ps
   SET costo_confirmado = TRUE
 WHERE ps.costo_confirmado = FALSE
   AND EXISTS (
     SELECT 1 FROM inventario_movimientos im
      WHERE im.producto_id = ps.producto_id
        AND im.sucursal_id = ps.sucursal_id
        AND im.tipo = 'ENTRADA_COMPRA'
   );

-- =============================================================================
-- Historial de costo, hermano de producto_precios
--
-- El costo mal tecleado no se podia corregir: `actualizar()` lo ignoraba a
-- proposito ("nunca el costo, que lo mueven las compras") y la unica salida era
-- inventar una entrada de mercancia, que ensucia el kardex y las cuentas por
-- pagar. Ahora se puede corregir, pero NO en silencio: toda correccion manual
-- deja fila aqui con el antes, el despues, quien y por que.
--
-- Las entradas de mercancia NO se registran en esta tabla: esas ya viven en
-- inventario_movimientos con su costo_promedio_anterior/posterior.
-- =============================================================================

CREATE TABLE IF NOT EXISTS producto_costos (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  producto_id     BIGINT NOT NULL,
  sucursal_id     BIGINT NOT NULL,
  costo_anterior  DECIMAL(14,4) NOT NULL CHECK (costo_anterior >= 0),
  costo_nuevo     DECIMAL(14,4) NOT NULL CHECK (costo_nuevo >= 0),
  era_semilla     BOOLEAN NOT NULL DEFAULT FALSE,
  cantidad_stock  DECIMAL(14,3) NOT NULL DEFAULT 0,
  motivo          VARCHAR(200),
  usuario_id      BIGINT NOT NULL,
  creado_en       TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_pcostos_producto FOREIGN KEY (producto_id) REFERENCES productos(id)  ON DELETE RESTRICT,
  CONSTRAINT fk_pcostos_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(id) ON DELETE RESTRICT,
  CONSTRAINT fk_pcostos_usuario  FOREIGN KEY (usuario_id)  REFERENCES usuarios(id)   ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS ix_pcostos_producto ON producto_costos (producto_id, creado_en);
CREATE INDEX IF NOT EXISTS ix_pcostos_usuario  ON producto_costos (usuario_id);

COMMENT ON TABLE producto_costos IS 'Historial de correcciones manuales de costo (revalorizacion). Las compras van en inventario_movimientos';
